### ISSUE TITLE
"Unable to load trainer file"

### ISSUE THREAD

**Issue by digginhut** [Retrobyte/Retrobyte#2]
I've tried to recompile this a few times and I still get this error. Is it only me? I have compiled it on linux and Windows.I cannot find a trainer file either. Any help would be greatly appreciated!

**Comment by Retrobyte** [comment]
Hi there! Sorry for the late reply, as well as my missing documentation for the trainer file. The trainer file is a text file named, "trainers.txt", and is located in the same directory as the application. Each line contains a format of "trainer_level:trainer_id" without the quotes of course, and you are supposed to create this file with the current training accounts available. A list of current training accounts can be found at: http://wiki.tppc.info/Training_Accounts

**Comment by digginhut** [comment]
What exactly does trainer level mean. I put the level of the trainers pokemon and it worked but it would just do " starting battle" "battle lost" even though I could easily beat the trainer with one hit ko's every time and I would never gain any levels either when I should every battle. Am I doing something wrong?

**Comment by Retrobyte** [comment]
Trainer level is the level of the pokemon on the trainer's team. Ideally, you would really only want to put a trainer in the list only if all his pokemon are about the same level. The bot uses a formula to decide whether your pokemon (assuming it's a fighting type pokemon with 120 attack) can OHKO the opposing pokemon (assuming it's a blissey) at the level specified before selecting a trainer to fight.
